//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputLayoutCodeGenerator
//     version 1.18.0
//     from "VirtualCursor" layout
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine.InputSystem;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.InputSystem.Utilities;

// Suppress warnings from local variables for control references that we don't end up using.
#pragma warning disable CS0219

// Suppress warnings from obsolete code when references from auto-generated code from the same code base.
#pragma warning disable CS0618

namespace Input
{
    public partial class FastVirtualCursor : Input.VirtualCursor
    {
        public const string metadata = "AutoWindowSpace;Vector2;Delta;Button;Axis;Analog;Integer;VirtualCursor;Pointer";
        public FastVirtualCursor()
        {
            var builder = this.Setup(23, 6, 2)
                .WithName("VirtualCursor")
                .WithDisplayName("VirtualCursor")
                .WithChildren(0, 7)
                .WithLayout(new InternedString("VirtualCursor"))
                .WithStateBlock(new InputStateBlock { format = new FourCC(1447253330), sizeInBits = 288 });

            var kVector2Layout = new InternedString("Vector2");
            var kDeltaLayout = new InternedString("Delta");
            var kButtonLayout = new InternedString("Button");
            var kAnalogLayout = new InternedString("Analog");
            var kIntegerLayout = new InternedString("Integer");
            var kAxisLayout = new InternedString("Axis");

            // /VirtualCursor/position
            var ctrlVirtualCursorposition = Initialize_ctrlVirtualCursorposition(kVector2Layout, this);

            // /VirtualCursor/delta
            var ctrlVirtualCursordelta = Initialize_ctrlVirtualCursordelta(kDeltaLayout, this);

            // /VirtualCursor/scroll
            var ctrlVirtualCursorscroll = Initialize_ctrlVirtualCursorscroll(kDeltaLayout, this);

            // /VirtualCursor/press
            var ctrlVirtualCursorpress = Initialize_ctrlVirtualCursorpress(kButtonLayout, this);

            // /VirtualCursor/pressure
            var ctrlVirtualCursorpressure = Initialize_ctrlVirtualCursorpressure(kAnalogLayout, this);

            // /VirtualCursor/radius
            var ctrlVirtualCursorradius = Initialize_ctrlVirtualCursorradius(kVector2Layout, this);

            // /VirtualCursor/displayIndex
            var ctrlVirtualCursordisplayIndex = Initialize_ctrlVirtualCursordisplayIndex(kIntegerLayout, this);

            // /VirtualCursor/position/x
            var ctrlVirtualCursorpositionx = Initialize_ctrlVirtualCursorpositionx(kAxisLayout, ctrlVirtualCursorposition);

            // /VirtualCursor/position/y
            var ctrlVirtualCursorpositiony = Initialize_ctrlVirtualCursorpositiony(kAxisLayout, ctrlVirtualCursorposition);

            // /VirtualCursor/delta/up
            var ctrlVirtualCursordeltaup = Initialize_ctrlVirtualCursordeltaup(kAxisLayout, ctrlVirtualCursordelta);

            // /VirtualCursor/delta/down
            var ctrlVirtualCursordeltadown = Initialize_ctrlVirtualCursordeltadown(kAxisLayout, ctrlVirtualCursordelta);

            // /VirtualCursor/delta/left
            var ctrlVirtualCursordeltaleft = Initialize_ctrlVirtualCursordeltaleft(kAxisLayout, ctrlVirtualCursordelta);

            // /VirtualCursor/delta/right
            var ctrlVirtualCursordeltaright = Initialize_ctrlVirtualCursordeltaright(kAxisLayout, ctrlVirtualCursordelta);

            // /VirtualCursor/delta/x
            var ctrlVirtualCursordeltax = Initialize_ctrlVirtualCursordeltax(kAxisLayout, ctrlVirtualCursordelta);

            // /VirtualCursor/delta/y
            var ctrlVirtualCursordeltay = Initialize_ctrlVirtualCursordeltay(kAxisLayout, ctrlVirtualCursordelta);

            // /VirtualCursor/scroll/up
            var ctrlVirtualCursorscrollup = Initialize_ctrlVirtualCursorscrollup(kAxisLayout, ctrlVirtualCursorscroll);

            // /VirtualCursor/scroll/down
            var ctrlVirtualCursorscrolldown = Initialize_ctrlVirtualCursorscrolldown(kAxisLayout, ctrlVirtualCursorscroll);

            // /VirtualCursor/scroll/left
            var ctrlVirtualCursorscrollleft = Initialize_ctrlVirtualCursorscrollleft(kAxisLayout, ctrlVirtualCursorscroll);

            // /VirtualCursor/scroll/right
            var ctrlVirtualCursorscrollright = Initialize_ctrlVirtualCursorscrollright(kAxisLayout, ctrlVirtualCursorscroll);

            // /VirtualCursor/scroll/x
            var ctrlVirtualCursorscrollx = Initialize_ctrlVirtualCursorscrollx(kAxisLayout, ctrlVirtualCursorscroll);

            // /VirtualCursor/scroll/y
            var ctrlVirtualCursorscrolly = Initialize_ctrlVirtualCursorscrolly(kAxisLayout, ctrlVirtualCursorscroll);

            // /VirtualCursor/radius/x
            var ctrlVirtualCursorradiusx = Initialize_ctrlVirtualCursorradiusx(kAxisLayout, ctrlVirtualCursorradius);

            // /VirtualCursor/radius/y
            var ctrlVirtualCursorradiusy = Initialize_ctrlVirtualCursorradiusy(kAxisLayout, ctrlVirtualCursorradius);

            // Usages.
            builder.WithControlUsage(0, new InternedString("Point"), ctrlVirtualCursorposition);
            builder.WithControlUsage(1, new InternedString("Secondary2DMotion"), ctrlVirtualCursordelta);
            builder.WithControlUsage(2, new InternedString("ScrollHorizontal"), ctrlVirtualCursorscrollx);
            builder.WithControlUsage(3, new InternedString("ScrollVertical"), ctrlVirtualCursorscrolly);
            builder.WithControlUsage(4, new InternedString("Pressure"), ctrlVirtualCursorpressure);
            builder.WithControlUsage(5, new InternedString("Radius"), ctrlVirtualCursorradius);

            // Aliases.
            builder.WithControlAlias(0,  new InternedString("horizontal"));
            builder.WithControlAlias(1,  new InternedString("vertical"));

            // Control getters/arrays.
            this.scroll = ctrlVirtualCursorscroll;
            this.position = ctrlVirtualCursorposition;
            this.delta = ctrlVirtualCursordelta;
            this.radius = ctrlVirtualCursorradius;
            this.pressure = ctrlVirtualCursorpressure;
            this.press = ctrlVirtualCursorpress;
            this.displayIndex = ctrlVirtualCursordisplayIndex;
            ctrlVirtualCursorposition.x = ctrlVirtualCursorpositionx;
            ctrlVirtualCursorposition.y = ctrlVirtualCursorpositiony;
            ctrlVirtualCursordelta.up = ctrlVirtualCursordeltaup;
            ctrlVirtualCursordelta.down = ctrlVirtualCursordeltadown;
            ctrlVirtualCursordelta.left = ctrlVirtualCursordeltaleft;
            ctrlVirtualCursordelta.right = ctrlVirtualCursordeltaright;
            ctrlVirtualCursordelta.x = ctrlVirtualCursordeltax;
            ctrlVirtualCursordelta.y = ctrlVirtualCursordeltay;
            ctrlVirtualCursorscroll.up = ctrlVirtualCursorscrollup;
            ctrlVirtualCursorscroll.down = ctrlVirtualCursorscrolldown;
            ctrlVirtualCursorscroll.left = ctrlVirtualCursorscrollleft;
            ctrlVirtualCursorscroll.right = ctrlVirtualCursorscrollright;
            ctrlVirtualCursorscroll.x = ctrlVirtualCursorscrollx;
            ctrlVirtualCursorscroll.y = ctrlVirtualCursorscrolly;
            ctrlVirtualCursorradius.x = ctrlVirtualCursorradiusx;
            ctrlVirtualCursorradius.y = ctrlVirtualCursorradiusy;

            // State offset to control index map.
            builder.WithStateOffsetToControlIndexMap(new uint[]
            {
                32775u, 16809992u, 33587211u, 33587212u, 33587213u, 50364425u, 50364426u, 50364430u, 67141649u, 67141650u
                , 67141651u, 83918852u, 83918863u, 83918864u, 83918868u, 100664323u, 100696085u, 117473302u, 142622726u
            });

            builder.WithControlTree(new byte[]
            {
                // Control tree nodes as bytes
                31, 1, 1, 0, 0, 0, 0, 128, 0, 3, 0, 0, 0, 0, 31, 1, 9, 0, 0, 0, 0, 64, 0, 5, 0, 0, 0, 1, 128, 0
                , 7, 0, 3, 0, 1, 32, 0, 255, 255, 1, 0, 1, 64, 0, 255, 255, 2, 0, 1, 96, 0, 255, 255, 7, 0, 3, 128, 0, 255, 255
                , 4, 0, 3, 192, 0, 11, 0, 10, 0, 1, 31, 1, 13, 0, 0, 0, 0, 160, 0, 255, 255, 15, 0, 3, 192, 0, 255, 255, 11, 0
                , 4, 16, 1, 15, 0, 0, 0, 0, 31, 1, 29, 0, 0, 0, 0, 232, 0, 17, 0, 19, 0, 2, 16, 1, 255, 255, 21, 0, 2, 212
                , 0, 19, 0, 23, 0, 1, 232, 0, 255, 255, 24, 0, 1, 202, 0, 21, 0, 0, 0, 0, 212, 0, 255, 255, 0, 0, 0, 197, 0, 23
                , 0, 0, 0, 0, 202, 0, 255, 255, 0, 0, 0, 195, 0, 25, 0, 0, 0, 0, 197, 0, 255, 255, 0, 0, 0, 194, 0, 27, 0, 0
                , 0, 0, 195, 0, 255, 255, 0, 0, 0, 193, 0, 255, 255, 18, 0, 1, 194, 0, 255, 255, 0, 0, 0, 24, 1, 255, 255, 25, 0, 1
                , 31, 1, 255, 255, 26, 0, 1
            }, new ushort[]
                {
                    // Control tree node indicies

                    0, 7, 8, 1, 9, 10, 14, 11, 12, 13, 2, 15, 16, 20, 4, 17, 18, 19, 3, 5, 22, 5, 22, 21, 21, 6, 6
                });

            builder.Finish();
        }

        private UnityEngine.InputSystem.Controls.Vector2Control Initialize_ctrlVirtualCursorposition(InternedString kVector2Layout, InputControl parent)
        {
            var ctrlVirtualCursorposition = new UnityEngine.InputSystem.Controls.Vector2Control();
            ctrlVirtualCursorposition.Setup()
                .At(this, 0)
                .WithParent(parent)
                .WithChildren(7, 2)
                .WithName("position")
                .WithDisplayName("Position")
                .WithLayout(kVector2Layout)
                .WithUsages(0, 1)
                .DontReset(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1447379762),
                    byteOffset = 0,
                    bitOffset = 0,
                    sizeInBits = 64
                })
                #if UNITY_EDITOR
                .WithProcessor<InputProcessor<UnityEngine.Vector2>, UnityEngine.Vector2>(new UnityEngine.InputSystem.Processors.EditorWindowSpaceProcessor())
                #endif
                .Finish();
            return ctrlVirtualCursorposition;
        }

        private UnityEngine.InputSystem.Controls.DeltaControl Initialize_ctrlVirtualCursordelta(InternedString kDeltaLayout, InputControl parent)
        {
            var ctrlVirtualCursordelta = new UnityEngine.InputSystem.Controls.DeltaControl();
            ctrlVirtualCursordelta.Setup()
                .At(this, 1)
                .WithParent(parent)
                .WithChildren(9, 6)
                .WithName("delta")
                .WithDisplayName("Delta")
                .WithLayout(kDeltaLayout)
                .WithUsages(1, 1)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1447379762),
                    byteOffset = 8,
                    bitOffset = 0,
                    sizeInBits = 64
                })
                .Finish();
            return ctrlVirtualCursordelta;
        }

        private UnityEngine.InputSystem.Controls.DeltaControl Initialize_ctrlVirtualCursorscroll(InternedString kDeltaLayout, InputControl parent)
        {
            var ctrlVirtualCursorscroll = new UnityEngine.InputSystem.Controls.DeltaControl();
            ctrlVirtualCursorscroll.Setup()
                .At(this, 2)
                .WithParent(parent)
                .WithChildren(15, 6)
                .WithName("scroll")
                .WithDisplayName("Scroll")
                .WithLayout(kDeltaLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1447379762),
                    byteOffset = 16,
                    bitOffset = 0,
                    sizeInBits = 64
                })
                .Finish();
            return ctrlVirtualCursorscroll;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlVirtualCursorpress(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlVirtualCursorpress = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlVirtualCursorpress.Setup()
                .At(this, 3)
                .WithParent(parent)
                .WithName("press")
                .WithDisplayName("Press")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 24,
                    bitOffset = 0,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlVirtualCursorpress;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursorpressure(InternedString kAnalogLayout, InputControl parent)
        {
            var ctrlVirtualCursorpressure = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlVirtualCursorpressure.Setup()
                .At(this, 4)
                .WithParent(parent)
                .WithName("pressure")
                .WithDisplayName("Pressure")
                .WithLayout(kAnalogLayout)
                .WithUsages(4, 1)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 20,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .WithDefaultState(1)
                .Finish();
            return ctrlVirtualCursorpressure;
        }

        private UnityEngine.InputSystem.Controls.Vector2Control Initialize_ctrlVirtualCursorradius(InternedString kVector2Layout, InputControl parent)
        {
            var ctrlVirtualCursorradius = new UnityEngine.InputSystem.Controls.Vector2Control();
            ctrlVirtualCursorradius.Setup()
                .At(this, 5)
                .WithParent(parent)
                .WithChildren(21, 2)
                .WithName("radius")
                .WithDisplayName("Radius")
                .WithLayout(kVector2Layout)
                .WithUsages(5, 1)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1447379762),
                    byteOffset = 24,
                    bitOffset = 0,
                    sizeInBits = 64
                })
                .Finish();
            return ctrlVirtualCursorradius;
        }

        private UnityEngine.InputSystem.Controls.IntegerControl Initialize_ctrlVirtualCursordisplayIndex(InternedString kIntegerLayout, InputControl parent)
        {
            var ctrlVirtualCursordisplayIndex = new UnityEngine.InputSystem.Controls.IntegerControl();
            ctrlVirtualCursordisplayIndex.Setup()
                .At(this, 6)
                .WithParent(parent)
                .WithName("displayIndex")
                .WithDisplayName("Display Index")
                .WithLayout(kIntegerLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1431521364),
                    byteOffset = 34,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .Finish();
            return ctrlVirtualCursordisplayIndex;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursorpositionx(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursorpositionx = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlVirtualCursorpositionx.Setup()
                .At(this, 7)
                .WithParent(parent)
                .WithName("x")
                .WithDisplayName("Position X")
                .WithShortDisplayName("Position X")
                .WithLayout(kAxisLayout)
                .DontReset(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 0,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursorpositionx;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursorpositiony(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursorpositiony = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlVirtualCursorpositiony.Setup()
                .At(this, 8)
                .WithParent(parent)
                .WithName("y")
                .WithDisplayName("Position Y")
                .WithShortDisplayName("Position Y")
                .WithLayout(kAxisLayout)
                .DontReset(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 4,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursorpositiony;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursordeltaup(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursordeltaup = new UnityEngine.InputSystem.Controls.AxisControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMax = 3.402823E+38f };
            ctrlVirtualCursordeltaup.Setup()
                .At(this, 9)
                .WithParent(parent)
                .WithName("up")
                .WithDisplayName("Delta Up")
                .WithShortDisplayName("Delta Up")
                .WithLayout(kAxisLayout)
                .IsSynthetic(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 12,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursordeltaup;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursordeltadown(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursordeltadown = new UnityEngine.InputSystem.Controls.AxisControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMin = -3.402823E+38f, invert = true };
            ctrlVirtualCursordeltadown.Setup()
                .At(this, 10)
                .WithParent(parent)
                .WithName("down")
                .WithDisplayName("Delta Down")
                .WithShortDisplayName("Delta Down")
                .WithLayout(kAxisLayout)
                .IsSynthetic(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 12,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursordeltadown;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursordeltaleft(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursordeltaleft = new UnityEngine.InputSystem.Controls.AxisControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMin = -3.402823E+38f, invert = true };
            ctrlVirtualCursordeltaleft.Setup()
                .At(this, 11)
                .WithParent(parent)
                .WithName("left")
                .WithDisplayName("Delta Left")
                .WithShortDisplayName("Delta Left")
                .WithLayout(kAxisLayout)
                .IsSynthetic(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 8,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursordeltaleft;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursordeltaright(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursordeltaright = new UnityEngine.InputSystem.Controls.AxisControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMax = 3.402823E+38f };
            ctrlVirtualCursordeltaright.Setup()
                .At(this, 12)
                .WithParent(parent)
                .WithName("right")
                .WithDisplayName("Delta Right")
                .WithShortDisplayName("Delta Right")
                .WithLayout(kAxisLayout)
                .IsSynthetic(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 8,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursordeltaright;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursordeltax(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursordeltax = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlVirtualCursordeltax.Setup()
                .At(this, 13)
                .WithParent(parent)
                .WithName("x")
                .WithDisplayName("Delta X")
                .WithShortDisplayName("Delta X")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 8,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursordeltax;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursordeltay(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursordeltay = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlVirtualCursordeltay.Setup()
                .At(this, 14)
                .WithParent(parent)
                .WithName("y")
                .WithDisplayName("Delta Y")
                .WithShortDisplayName("Delta Y")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 12,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursordeltay;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursorscrollup(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursorscrollup = new UnityEngine.InputSystem.Controls.AxisControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMax = 3.402823E+38f };
            ctrlVirtualCursorscrollup.Setup()
                .At(this, 15)
                .WithParent(parent)
                .WithName("up")
                .WithDisplayName("Scroll Up")
                .WithShortDisplayName("Scroll Up")
                .WithLayout(kAxisLayout)
                .IsSynthetic(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 20,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursorscrollup;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursorscrolldown(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursorscrolldown = new UnityEngine.InputSystem.Controls.AxisControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMin = -3.402823E+38f, invert = true };
            ctrlVirtualCursorscrolldown.Setup()
                .At(this, 16)
                .WithParent(parent)
                .WithName("down")
                .WithDisplayName("Scroll Down")
                .WithShortDisplayName("Scroll Down")
                .WithLayout(kAxisLayout)
                .IsSynthetic(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 20,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursorscrolldown;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursorscrollleft(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursorscrollleft = new UnityEngine.InputSystem.Controls.AxisControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMin = -3.402823E+38f, invert = true };
            ctrlVirtualCursorscrollleft.Setup()
                .At(this, 17)
                .WithParent(parent)
                .WithName("left")
                .WithDisplayName("Scroll Left")
                .WithShortDisplayName("Scroll Left")
                .WithLayout(kAxisLayout)
                .IsSynthetic(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 16,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursorscrollleft;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursorscrollright(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursorscrollright = new UnityEngine.InputSystem.Controls.AxisControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMax = 3.402823E+38f };
            ctrlVirtualCursorscrollright.Setup()
                .At(this, 18)
                .WithParent(parent)
                .WithName("right")
                .WithDisplayName("Scroll Right")
                .WithShortDisplayName("Scroll Right")
                .WithLayout(kAxisLayout)
                .IsSynthetic(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 16,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursorscrollright;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursorscrollx(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursorscrollx = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlVirtualCursorscrollx.Setup()
                .At(this, 19)
                .WithParent(parent)
                .WithName("x")
                .WithDisplayName("Scroll Left/Right")
                .WithShortDisplayName("Scroll Left/Right")
                .WithLayout(kAxisLayout)
                .WithUsages(2, 1)
                .WithAliases(0, 1)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 16,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursorscrollx;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursorscrolly(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursorscrolly = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlVirtualCursorscrolly.Setup()
                .At(this, 20)
                .WithParent(parent)
                .WithName("y")
                .WithDisplayName("Scroll Up/Down")
                .WithShortDisplayName("Scroll Up/Down")
                .WithLayout(kAxisLayout)
                .WithUsages(3, 1)
                .WithAliases(1, 1)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 20,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursorscrolly;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursorradiusx(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursorradiusx = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlVirtualCursorradiusx.Setup()
                .At(this, 21)
                .WithParent(parent)
                .WithName("x")
                .WithDisplayName("Radius X")
                .WithShortDisplayName("Radius X")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 24,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursorradiusx;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlVirtualCursorradiusy(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlVirtualCursorradiusy = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlVirtualCursorradiusy.Setup()
                .At(this, 22)
                .WithParent(parent)
                .WithName("y")
                .WithDisplayName("Radius Y")
                .WithShortDisplayName("Radius Y")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1179407392),
                    byteOffset = 28,
                    bitOffset = 0,
                    sizeInBits = 32
                })
                .Finish();
            return ctrlVirtualCursorradiusy;
        }
    }
}
